apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  # - kiali.yaml
  - prometheus.yaml

images:
- name: docker.io/jimmidyson/configmap-reload:v0.8.0
  newName: docker.io/jimmidyson/configmap-reload
  newTag: v0.8.0
- name: docker.io/prom/prometheus:v2.41.0
  newName: docker.io/chainguard/prometheus
  newTag: latest
# - name: quay.io/kiali/kiali:v1.72
#   newName: harbor.csde.caci.com/registry1.dso.mil/ironbank/opensource/kiali/kiali
#   newTag: v1.72.0
- name: docker.io/grafana/grafana:9.5.5
  newName: docker.io/chainguard/grafana
  newTag: latest