---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: istio-ingress
spec:
  workloads:
    - selector:
        labels:
          app: istio-ingress
        cluster: mgmt
  listeners: 
    - http: {}
      port:
        number: 80
      allowedRouteTables:
        - host: '*'
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin
  namespace: httpbin
spec:
  hosts:
    - 'httpbin.example.com'
  virtualGateways:
    - name: north-south-gw
      namespace: istio-ingress
      cluster: mgmt
  http:
  - matchers:
    - uri:
        prefix: /
        ignoreCase: true
    forwardTo:
      destinations:
      - ref:
          name: httpbin
          namespace: httpbin
          cluster: mgmt
        port:
          number: 8000
        kind: SERVICE
