# To setup STRICT mTLS in the istio service mesh
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-strict-mtls
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  mtls:
    mode: STRICT