common:
  cluster: mgmt
glooInsightsEngine:
  enabled: false
glooMgmtServer:
  enabled: true
  createGlobalWorkspace: true
  ports:
    healthcheck: 8091
glooAgent:
  enabled: true
  relay:
    authority: gloo-mesh-mgmt-server.gloo-mesh
    serverAddress: 172.18.101.3:9900
glooUi:
  enabled: true
licensing:
  glooTrialLicenseKey: <mesh-key>
prometheus:
  enabled: true
redis:
  deployment:
    enabled: true
telemetryCollector:
  config:
    exporters:
      otlp:
        endpoint: gloo-telemetry-gateway:4317
  enabled: true
telemetryColectorCustomization:
  extraExporters:
    datadog:
      api:
        site: us5.datadoghq.com
        key: d2cfb42e2b92c2ef8d16ee64f8631ab9
  extraPipelines:
    metrics/export-to-datadog:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      exporters:
      - datadog
telemetryGatewayCustomization:
  extraExporters:
    datadog:
      api:
        site: us5.datadoghq.com
        key: d2cfb42e2b92c2ef8d16ee64f8631ab9
  extraPipelines:
    metrics/workload-clusters:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      exporters:
      - datadog
telemetryGateway:
  enabled: true
  service:
    type: LoadBalancer
