---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-platform-oss-istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.2
    helm:
      values: |
        global:
          meshID: gloo-mesh
          multiCluster:
            clusterName: gloo-mesh-workload-cluster-1
          network: gloo-mesh-workload-cluster-1
          hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
          tag: 1.20.2-solo
        meshConfig:
          accessLogFile: /dev/stdout
          accessLogEncoding: JSON
          enableAutoMtls: true
          defaultConfig:
            # Wait for the istio-proxy to start before starting application pods
            holdApplicationUntilProxyStarts: true
            proxyMetadata:
              # Enable Istio agent to handle DNS requests for known hosts
              # Unknown hosts are automatically resolved using upstream DNS servers
              # in resolv.conf (for proxy-dns)
              ISTIO_META_DNS_CAPTURE: "true"
              # Enable automatic address allocation (for proxy-dns)
              ISTIO_META_DNS_AUTO_ALLOCATE: "true"
          outboundTrafficPolicy:
            mode: ALLOW_ANY
          rootNamespace: istio-system
        pilot:
          env:
            # Disable selecting workload entries for local service routing.
            # Required for Gloo VirtualDestinaton functionality.
            PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES: "false"
            # Skip validating the peer is from the same trust domain when mTLS is enabled in authentication policy
            PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
