---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-platform-oss-istio-ingressgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-gateways
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.2
    helm:
      values: |
        name: "istio-ingressgateway-1-20"
        # Labels to apply to all resources
        labels:
          istio: ingressgateway
          app: istio-ingressgateway-1-20
        service:
          type: "None"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
