apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: gloo-agent-wl-cluster
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-platform
    helm:
      skipCrds: true
      values: |
        common:
          cluster: cluster1
        glooAgent:
          enabled: true
          relay:
            # "${GLOO_PLATFORM_MGMT_SERVER_ADDRESS}"
            serverAddress: 172.18.101.2:9900
        telemetryCollector:
          enabled: true
          config:
            exporters:
              otlp:
                # "${GLOO_PLATFORM_TELEMETRY_GATEWAY_ADDRESS}"
                endpoint: 172.18.101.3:4317
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
    targetRevision: 2.5.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true