apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: gloo-platform-helm
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-platform
    helm:
      skipCrds: true
      values: |
        licensing:
          glooMeshLicenseKey: "eyJhZGRPbnMiOltdLCJleHAiOjE3MjE3Nzc1MzksImlhdCI6MTY2MTI5NzUzOSwiayI6InY2Z2o2ZyIsImx0IjoiZW50IiwicHJvZHVjdCI6Imdsb28tbWVzaC1nYXRld2F5In0.xLmjo9mWQlQpCnAYdOtqbOo6yL1L8-0mBKN0FgUPxXk"
          # glooGatewayLicenseKey: ""
          # glooNetworkLicenseKey: ""
        common:
          cluster: mgmt-cluster-arka
        glooMgmtServer:
          enabled: true
          agents:
            - name: cluster-1-arka
            - name: cluster-2-arka
          serviceType: LoadBalancer
          serviceOverrides:
            metadata:
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        prometheus:
          enabled: true
        redis:
          deployment:
            enabled: true
        glooUi:
          enabled: true
        telemetryGateway:
          enabled: true
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
    targetRevision: 2.5.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
