apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: gloo-platform-helm
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-platform
    helm:
      skipCrds: true
      values: |
        licensing:
          glooMeshLicenseKey: "REDACTED"
          # glooGatewayLicenseKey: ""
          # glooNetworkLicenseKey: ""
        common:
          cluster: mgmt
        glooMgmtServer:
          enabled: true
          agents:
            - name: cluster1
          serviceType: LoadBalancer
          # serviceOverrides:
          #   metadata:
          #     annotations:
          #       service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        prometheus:
          enabled: true
        redis:
          deployment:
            enabled: true
        glooUi:
          enabled: true
        telemetryGateway:
          enabled: true
          service:
            type: LoadBalancer
            # annotations:
            #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        telemetryCollector:
          enabled: true
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
    targetRevision: 2.5.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
